name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.5
      - name: Run feed generator
        uses: sagar-qa007/GitHubCustomAction@main
